---
title: "Research"
---

<!-- One paragraph per paper, newest (top) to oldest (bottom). Probably use a standard APSA style. Include a DOI and hyperlink for all published papers. If you have polished working papers, include links to those as well. -->

My research analyzes both elite and public response to international crises. I study both how elites shape and react to crises through framing, strategic interaction, and overt opposition, as well as how the public responds to foreign policy decisions in crisis. A complete list is on my [CV](Robbins_CV.pdf).

## Peer-Reviewed Articles

## Under Review

Boldt, Damian and Robbins, Caroline. 2026. "Something is Rotten in the Alliance: Democratic Backsliding Reduces Public Support for Aiding Allies." Under Review, *American Journal of Political Science*.

Rainey, C., Robbins, C., Brunelli, A., Castro, J., Coty, A., Louis, A., Major, B., Martínez, A., Ojeda, Y., Pontes, L, Schumacher, E., Turkomer, O., Valenzuela, L., Veras, V. 2023. "Overt Consequences for Covert Actions: Secrecy and Accountability in Democracies." Revise and resubmit, *Journal of Experimental Political Science*.

## Working Papers

Milliff, A., Li, Y., Reeds, B., and Robbins, C. 2026. "Dis-Endorsement Messages Attrit Public Approval of Vigilante Violence: Evidence from India."

Hill, T., Holland, S., Robbins, C., Horuichi, Y. 2026. "Conjoint Analysis in Political Science: Current Practices and Future Directions."

Robbins, Caroline. 2026. "Crises and Coverage: The Effect of Crisis Density on Media Coverage of the International Information Environment."

Robbins, Caroline. 2026. "No More Wars*: Introducing International Type II Audience Costs."

Robbins, Caroline. 2026. "Strategic Chaos: Elite Manipulation of and Response to Concurrent International Crises."

Robbins, Caroline. 2025. "Sage Advice? The Effect of Relative Adviser Experience on Hawkish Foreign Policy Decisionmaking."

Robbins, Caroline. 2025. "Still Defending Democracy? Evolution of the Democratic Defense Norm in the Russian Invasion of Ukraine."

Robbins, Caroline. 2025. "Understanding Populism: Introducing a Typology of Benefits, Beneficiaries, and the Evolution of Populism in Democratic Contexts."

Hill, Taylor and Robbins, Caroline. 2026. "Public Tolerance for Democratic Backsliding in Domestic Versus Foreign Policy."

## Book Chapters